CREATE TABLE RACE_FAMILIES
(
    FAMILY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FAMILY_NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (FAMILY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE RACE_COMPETITORS
    ADD FAMILY_ID INT UNSIGNED;

ALTER TABLE RACE_COMPETITORS
    ADD CONSTRAINT FK_RACE_COMPETITORS_FAMILIES FOREIGN KEY (FAMILY_ID)
    REFERENCES RACE_FAMILIES(FAMILY_ID);
