CREATE TABLE IF NOT EXISTS MAP_TRACKS (
  TRACK_ID CHAR(36) NOT NULL,
  TRACK_NAME VARCHAR(255) NOT NULL,
  TRACK_CENTER VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(8192),
  LINE GEOMETRY NOT NULL,
  SHOW_BY_DEFAULT TINYINT(1) NOT NULL DEFAULT 0,
  SYMBOL_SVG LONGTEXT,
  ORDER_BY INT NOT NULL DEFAULT 0,
  PRIMARY KEY (TRACK_ID),
  SPATIAL INDEX (LINE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
