UPDATE RACE_CLASS_LEVEL
SET DIFFICULTY = 'Violett'
WHERE DIFFICULTY = 'Lila';

UPDATE RACE_EVENT_RESULTS
SET DIFFICULTY = 'Violett'
WHERE DIFFICULTY = 'Lila';

UPDATE RACE_EVENT_RESULTS_TEAM
SET DIFFICULTY = 'Violett'
WHERE DIFFICULTY = 'Lila';
