CREATE TABLE CALENDAR_RACE_EVENT
(
    CALENDAR_EVENT_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    EVENTOR_ID INT UNSIGNED,
    EVENTOR_RACE_ID INT UNSIGNED,
    NAME VARCHAR(128) NOT NULL,
    ORGANISER_NAME VARCHAR(128) NOT NULL,
    RACEDATE DATE NOT NULL,
    RACETIME DATETIME,
    LONGITUDE DECIMAL(20, 10),
    LATITUDE DECIMAL(20, 10),
    PRIMARY KEY (CALENDAR_EVENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;